namespace Snobol4.Common;

public class CompilerException : Exception
{
    #region Members

    public int Code { get; set; }
    public int Column { get; set; }
    public new string Message { get; set; }

    #endregion

    #region Constructors

                public CompilerException(int error, int column)
    {
        Code = error;
        Column = column;
        Message = "";
    }

                public CompilerException(int error)
    {
        Code = error;
        Column = 0;
        Message = "";
    }

    #endregion

    #region Error Messages

                            internal static readonly string[] ErrorMessage =
    [
        "no error" /* 0 */,
        "addition left operand is not numeric" /* 1 */,
        "addition right operand is not numeric" /* 2 */,
        "addition caused integer overflow" /* 3 */,
        "affirmation operand is not numeric" /* 4 */,
        "alternation right operand is not pattern" /* 5 */,
        "alternation left operand is not pattern" /* 6 */,
        "compilation error encountered during execution" /* 7 */,
        "concatenation left operand is not a string or pattern" /* 8 */,
        "concatenation right operand is not a string or pattern" /* 9 */,
        "negation operand is not numeric" /* 10 */,
        "negation caused integer overflow" /* 11 */,
        "division left operand is not numeric" /* 12 */,
        "division right operand is not numeric" /* 13 */,
        "division caused integer overflow" /* 14 */,
        "exponentiation right operand is not numeric" /* 15 */,
        "exponentiation left operand is not numeric" /* 16 */,
        "exponentiation caused integer overflow" /* 17 */,
        "exponentiation result is undefined" /* 18 */,
        "RESERVED" /* 19 */,
        "goto evaluation failure" /* 20 */,
        "function called by name returned a value" /* 21 */,
        "undefined function called" /* 22 */,
        "goto operand is not a natural variable" /* 23 */,
        "goto operand in direct goto is not code" /* 24 */,
        "immediate assignment left operand is not pattern" /* 25 */,
        "multiplication left operand is not numeric" /* 26 */,
        "multiplication right operand is not numeric" /* 27 */,
        "multiplication caused integer overflow" /* 28 */,
        "undefined operator referenced" /* 29 */,
        "pattern assignment left operand is not pattern" /* 30 */,
        "pattern replacement right operand is not a string" /* 31 */,
        "subtraction left operand is not numeric" /* 32 */,
        "subtraction right operand is not numeric" /* 33 */,
        "subtraction caused integer overflow" /* 34 */,
        "unexpected failure in -nofail mode" /* 35 */,
        "goto abort with no preceding error" /* 36 */,
        "goto continue with no preceding error" /* 37 */,
        "goto undefined label" /* 38 */,
        "external function argument is not a string" /* 39 */,
        "external function argument is not integer" /* 40 */,
        "field function argument is wrong datatype" /* 41 */,
        "attempt to change value of protected variable" /* 42 */,
        "any evaluated argument is not a string" /* 43 */,
        "break evaluated argument is not a string" /* 44 */,
        "breakx evaluated argument is not a string" /* 45 */,
        "expression does not evaluate to pattern" /* 46 */,
        "len evaluated argument is not integer" /* 47 */,
        "len evaluated argument is negative or too large" /* 48 */,
        "notany evaluated argument is not a string" /* 49 */,
        "pos evaluated argument is not integer" /* 50 */,
        "pos evaluated argument is negative or too large" /* 51 */,
        "rpos evaluated argument is not integer" /* 52 */,
        "rpos evaluated argument is negative or too large" /* 53 */,
        "rtab evaluated argument is not integer" /* 54 */,
        "rtab evaluated argument is negative or too large" /* 55 */,
        "span evaluated argument is not a string" /* 56 */,
        "tab evaluated argument is not integer" /* 57 */,
        "tab evaluated argument is negative or too large" /* 58 */,
        "any argument is not a string or expression" /* 59 */,
        "apply first arg is not natural variable name" /* 60 */,
        "arbno argument is not pattern" /* 61 */,
        "arg second argument is not integer" /* 62 */,
        "arg first argument is not program function name" /* 63 */,
        "array first argument is not integer or string" /* 64 */,
        "array first argument lower bound is not integer" /* 65 */,
        "array first argument upper bound is not integer" /* 66 */,
        "array dimension is zero negative or out of range" /* 67 */,
        "array size exceeds maximum permitted" /* 68 UNUSED*/,
        "break argument is not a string or expression" /* 69 */,
        "breakx argument is not a string or expression" /* 70 */,
        "clear argument is not a string" /* 71 */,
        "clear argument has null variable name" /* 72 */,
        "collect argument is not integer" /* 73 */,
        "convert second argument is not a string" /* 74 */,
        "data argument is not a string" /* 75 */,
        "data argument is null" /* 76 */,
        "data argument is missing a left paren" /* 77 */,
        "data argument has null datatype name" /* 78 */,
        "data argument is missing a right paren" /* 79 */,
        "data argument has null field name" /* 80 */,
        "define first argument is not a string" /* 81 */,
        "define first argument is null" /* 82 */,
        "define first argument is missing a left paren" /* 83 */,
        "define first argument has null function name" /* 84 */,
        "null arg name or missing ) in define first arg." /* 85 */,
        "define function entry point is not defined label" /* 86 */,
        "detach argument is not appropriate name" /* 87 */,
        "dump argument is not integer" /* 88 */,
        "dump argument is negative or too large" /* 89 */,
        "dupl second argument is not integer" /* 90 */,
        "dupl first argument is not a string or pattern" /* 91 */,
        "eject argument is not a suitable name" /* 92 */,
        "eject file does not exist" /* 93 */,
        "eject file does not permit page eject" /* 94 */,
        "eject caused non-recoverable output error" /* 95 */,
        "endfile argument is not a suitable name" /* 96 */,
        "endfile argument is null" /* 97 */,
        "endfile file does not exist" /* 98 */,
        "endfile file does not permit endfile" /* 99 */,
        "endfile caused non-recoverable output error" /* 100 */,
        "eq first argument is not numeric" /* 101 */,
        "eq second argument is not numeric" /* 102 */,
        "eval argument is not expression" /* 103 */,
        "exit first argument is not suitable integer or string" /* 104 */,
        "exit action not available in this implementation" /* 105 */,
        "exit action caused irrecoverable error" /* 106 */,
        "field second argument is not integer" /* 107 */,
        "field first argument is not datatype name" /* 108 */,
        "ge first argument is not numeric" /* 109 */,
        "ge second argument is not numeric" /* 110 */,
        "gt first argument is not numeric" /* 111 */,
        "gt second argument is not numeric" /* 112 */,
        "input third argument is not a string" /* 113 */,
        "inappropriate second argument for input" /* 114 */,
        "inappropriate first argument for input" /* 115 */,
        "inappropriate file specification for input" /* 116 */,
        "input file cannot be read" /* 117 */,
        "le first argument is not numeric" /* 118 */,
        "le second argument is not numeric" /* 119 */,
        "len argument is not integer or expression" /* 120 */,
        "len argument is negative or too large" /* 121 */,
        "leq first argument is not a string" /* 122 */,
        "leq second argument is not a string" /* 123 */,
        "lge first argument is not a string" /* 124 */,
        "lge second argument is not a string" /* 125 */,
        "lgt first argument is not a string" /* 126 */,
        "lgt second argument is not a string" /* 127 */,
        "lle first argument is not a string" /* 128 */,
        "lle second argument is not a string" /* 129 */,
        "llt first argument is not a string" /* 130 */,
        "llt second argument is not a string" /* 131 */,
        "lne first argument is not a string" /* 132 */,
        "lne second argument is not a string" /* 133 */,
        "local second argument is not integer" /* 134 */,
        "local first arg is not a program function name" /* 135 */,
        "load second argument is not a string" /* 136 */,
        "load first argument is not a string" /* 137 */,
        "load first argument is null" /* 138 */,
        "load first argument is missing a left paren" /* 139 */,
        "load first argument has null function name" /* 140 */,
        "load first argument is missing a right paren" /* 141 */,
        "load function does not exist" /* 142 */,
        "load function caused input error during load" /* 143 */,
        "lpad third argument is not a string" /* 144 */,
        "lpad second argument is not integer" /* 145 */,
        "lpad first argument is not a string" /* 146 */,
        "lt first argument is not numeric" /* 147 */,
        "lt second argument is not numeric" /* 148 */,
        "ne first argument is not numeric" /* 149 */,
        "ne second argument is not numeric" /* 150 */,
        "notany argument is not a string or expression" /* 151 */,
        "opsyn third argument is not integer" /* 152 */,
        "opsyn third argument is negative or too large" /* 153 */,
        "opsyn second arg is not natural variable name" /* 154 */,
        "opsyn first arg is not natural variable name" /* 155 */,
        "opsyn first arg is not correct operator name" /* 156 */,
        "output third argument is not a string" /* 157 */,
        "inappropriate second argument for output" /* 158 */,
        "inappropriate first argument for output" /* 159 */,
        "inappropriate file specification for output" /* 160 */,
        "output file cannot be written to" /* 161 */,
        "pos argument is not integer or expression" /* 162 */,
        "pos argument is negative or too large" /* 163 */,
        "prototype argument is not valid object" /* 164 */,
        "remdr second argument is not numeric" /* 165 */,
        "remdr first argument is not numeric" /* 166 */,
        "remdr caused integer overflow" /* 167 */,
        "replace third argument is not a string" /* 168 */,
        "replace second argument is not a string" /* 169 */,
        "replace first argument is not a string" /* 170 */,
        "null or unequally long 2nd 3rd args to replace" /* 171 */,
        "rewind argument is not a suitable name" /* 172 */,
        "rewind argument is null" /* 173 */,
        "rewind file does not exist" /* 174 */,
        "rewind file does not permit rewind" /* 175 */,
        "rewind caused non-recoverable error" /* 176 */,
        "reverse argument is not a string" /* 177 */,
        "rpad third argument is not a string" /* 178 */,
        "rpad second argument is not integer" /* 179 */,
        "rpad first argument is not a string" /* 180 */,
        "rtab argument is not integer or expression" /* 181 */,
        "rtab argument is negative or too large" /* 182 */,
        "tab argument is not integer or expression" /* 183 */,
        "tab argument is negative or too large" /* 184 */,
        "rpos argument is not integer or expression" /* 185 */,
        "rpos argument is negative or too large" /* 186 */,
        "setexit argument is not label name or null" /* 187 */,
        "span argument is not a string or expression" /* 188 */,
        "size argument is not a string" /* 189 */,
        "stoptr first argument is not appropriate name" /* 190 */,
        "stoptr second argument is not trace type" /* 191 */,
        "substr third argument is not integer" /* 192 */,
        "substr second argument is not integer" /* 193 */,
        "substr first argument is not a string" /* 194 */,
        "table argument is not integer" /* 195 UNUSED*/,
        "table argument is out of range" /* 196 UNUSED*/,
        "trace fourth arg is not function name or null" /* 197 */,
        "trace first argument is not appropriate name" /* 198 */,
        "trace second argument is not trace type" /* 199 */,
        "trim argument is not a string" /* 200 */,
        "unload argument is not natural variable name" /* 201 */,
        "input from file caused non-recoverable error" /* 202 */,
        "input file record has incorrect format" /* 203 */,
        "memory overflow" /* 204 */,
        "string length exceeds value of maxlngth keyword" /* 205 */,
        "output caused file overflow" /* 206 */,
        "output caused non-recoverable error" /* 207 */,
        "keyword value assigned is not integer" /* 208 */,
        "keyword in assignment is protected" /* 209 */,
        "keyword value assigned is negative or too large" /* 210 */,
        "value assigned to keyword errtext not a string" /* 211 */,
        "syntax error: value used where name is required" /* 212 */,
        "syntax error: statement is too complicated." /* 213 */,
        "bad label or misplaced continuation line" /* 214 */,
        "syntax error: undefined or erroneous entry label" /* 215 */,
        "syntax error: missing end line" /* 216 */,
        "syntax error: duplicate label" /* 217 */,
        "syntax error: duplicated goto field" /* 218 */,
        "syntax error: empty goto field" /* 219 */,
        "syntax error: missing operator" /* 220 */,
        "syntax error: missing operand" /* 221 */,
        "syntax error: invalid use of left bracket" /* 222 */,
        "syntax error: invalid use of comma" /* 223 */,
        "syntax error: unbalanced right parenthesis" /* 224 */,
        "syntax error: unbalanced right bracket" /* 225 */,
        "syntax error: missing right paren" /* 226 */,
        "syntax error: right paren missing from goto" /* 227 */,
        "syntax error: right bracket missing from goto" /* 228 */,
        "syntax error: missing right array bracket" /* 229 */,
        "syntax error: illegal character" /* 230 */,
        "syntax error: invalid numeric item" /* 231 */,
        "syntax error: unmatched string quote" /* 232 */,
        "syntax error: invalid use of operator" /* 233 */,
        "syntax error: goto field incorrect" /* 234 */,
        "subscripted operand is not table or array" /* 235 */,
        "array referenced with wrong number of subscripts" /* 236 */,
        "table referenced with more than one subscript" /* 237 */,
        "array subscript is not integer" /* 238 */,
        "indirection operand is not name" /* 239 */,
        "pattern match right operand is not pattern" /* 240 */,
        "pattern match left operand is not a string" /* 241 */,
        "function return from level zero" /* 242 */,
        "function result in nreturn is not name" /* 243 */,
        "statement count exceeds value of stlimit keyword" /* 244 */,
        "translation/execution time expired" /* 245 */,
        "stack overflow" /* 246 */,
        "invalid control statement" /* 247 */,
        "attempted redefinition of system function" /* 248 */,
        "expression evaluated by name returned value" /* 249 */,
        "insufficient memory to complete dump" /* 250 */,
        "keyword operand is not name of defined keyword" /* 251 */,
        "error on printing to interactive channel" /* 252 */,
        "print limit exceeded on standard output channel" /* 253 */,
        "erroneous argument for host" /* 254 */,
        "error during execution of host" /* 255 */,
        "sort/rsort 1st arg not suitable array or table" /* 256 */,
        "erroneous 2nd arg in sort/rsort of vector" /* 257 */,
        "sort/rsort 2nd arg out of range or non-integer" /* 258 */,
        "fence argument is not pattern" /* 259 */,
        "conversion array size exceeds maximum permitted" /* 260 UNUSED*/,
        "addition caused real overflow" /* 261 */,
        "division caused real overflow" /* 262 */,
        "multiplication caused real overflow" /* 263 */,
        "subtraction caused real overflow" /* 264 */,
        "external function argument is not real" /* 265 */,
        "exponentiation caused real overflow" /* 266 */,
        "RESERVED" /* 267 */,
        "inconsistent value assigned to keyword profile" /* 268 */,
        "RESERVED" /* 269 */,
        "RESERVED" /* 270 */,
        "RESERVED" /* 271 */,
        "RESERVED" /* 272 */,
        "RESERVED" /* 273 */,
        "value assigned to keyword fullscan is zero" /* 274 */,
        "RESERVED" /* 275 */,
        "RESERVED" /* 276 */,
        "RESERVED" /* 277 */,
        "RESERVED" /* 278 */,
        "RESERVED" /* 279 */,
        "RESERVED" /* 280 */,
        "char argument not integer" /* 281 */,
        "char argument not in range" /* 282 */,
        "RESERVED" /* 283 */,
        "excessively nested include files" /* 284 */,
        "include file cannot be opened" /* 285 */,
        "function call to undefined entry label" /* 286 */,
        "value assigned to keyword maxlngth is too small" /* 287 */,
        "exit second argument is not a string" /* 288 */,
        "input channel currently in use" /* 289 */,
        "output channel currently in use" /* 290 */,

        // Added
        "set first argument is not a suitable name" /* 291 */,
        "set first argument is null" /* 292 */,
        "inappropriate second argument to set" /* 293 */,
        "inappropriate third argument to set" /* 294 */,
        "set file does not exist" /* 295 */,
        "set file does not permit setting file pointer" /* 296 */,
        "set caused non-recoverable I/O error" /* 297 */,

        "external function argument is not file" /* 298 */,
        "internal logic error   : unexpected ppm branch" /* 299 */,
        "RESERVED" /* 300 */,
        "atan argument not numeric" /* 301 */,
        "chop argument not numeric" /* 302 */,
        "cos argument not numeric" /* 303 */,
        "exp argument not numeric" /* 304 */,
        "exp produced real overflow" /* 305 */,
        "ln argument not numeric" /* 306 */,
        "ln produced real overflow" /* 307 */,
        "sin argument not numeric" /* 308 */,
        "tan argument not numeric" /* 309 */,
        "tan produced real overflow or argument is out of range" /* 310 */,
        "exponentiation of negative base to non-integral power" /* 311 */,
        "remdr caused real overflow" /* 312 */,
        "sqrt argument not numeric" /* 313 */,
        "sqrt argument negative" /* 314 */,
        "ln argument negative" /* 315 */,
        "backspace argument is not a suitable name" /* 316 */,
        "backspace file does not exist" /* 317 */,
        "backspace file does not permit backspace" /* 318 */,
        "backspace caused non-recoverable error" /* 319 */,
        "user interrupt" /* 320 */,
        "goto scontinue with no preceding error" /* 321 */,
        "cos argument is out of range" /* 322 */,
        "sin argument is out of range" /* 323 */,
        "RESERVED" /* 324 */,
        "RESERVED" /* 325 */,
        "calling external function - bad argument type" /* 326 */,
        "calling external function - not found" /* 327 */,
        "load function - insufficient memory" /* 328 */,
        "requested maxlngth too large" /* 329 */,
        "date argument is not integer" /* 330 */,
        "goto scontinue with no user interrupt" /* 331 */,
        "goto continue with error in failure goto" /* 332 */
    ];

    #endregion
}